site_name: Python Programs
docs_dir: .github/docs
theme:
  name: material
  palette:
  - scheme: default
    primary: indigo
    accent: pink
    toggle:
      icon: material/weather-night
      name: Switch to dark mode
  - scheme: slate
    primary: indigo
    accent: pink
    toggle:
      icon: material/weather-sunny
      name: Switch to light mode
  features:
  - navigation.instant
  - navigation.expand
  - navigation.sections
  - navigation.path
  - navigation.prune
  - search.highlight
  - search.suggest
  - content.code.copy
markdown_extensions:
- admonition
- codehilite
- footnotes
- tables
- toc
- pymdownx.highlight:
    anchor_linenums: true
    linenums: true
    linenums_style: table
    use_pygments: true
- pymdownx.superfences
extra_css:
- assets/extra.css
plugins:
- search
- offline
- tags
- table-reader
- mkdocs-jupyter:
    include:
    - '*.ipynb'
repo_url: https://github.com/SpreadSheets600/Python-Programs
repo_name: Python-Programs
nav:
- Home:
  - Home: README.md
  - Theory: ./Theory.md
- 29-07-2025:
  - Program 1: 29-07-2025/Program-1.md
  - Program 2: 29-07-2025/Program-2.md
  - Program 3: 29-07-2025/Program-3.md
  - Program 4: 29-07-2025/Program-4.md
  - Program 5: 29-07-2025/Program-5.md
  - Program 6: 29-07-2025/Program-6.md
  - Program 7: 29-07-2025/Program-7.md
  - README: 29-07-2025/README.md
- Assignment:
  - Assignment 1:
    - Program 1: Assignment/Assignment 1/Program-1.md
    - Program 2: Assignment/Assignment 1/Program-2.md
    - Program 3: Assignment/Assignment 1/Program-3.md
    - Program 4: Assignment/Assignment 1/Program-4.md
    - README: Assignment/Assignment 1/README.md
- Homework:
  - Homework 1:
    - Program 1: Homework/Homework 1/Program-1.md
    - Program 2: Homework/Homework 1/Program-2.md
    - Program 3: Homework/Homework 1/Program-3.md
    - Program 4: Homework/Homework 1/Program-4.md
    - Program 5: Homework/Homework 1/Program-5.md
    - Program 6: Homework/Homework 1/Program-6.md
    - Program 7: Homework/Homework 1/Program-7.md
    - README: Homework/Homework 1/README.md
  - Homework 2:
    - Program 1: Homework/Homework 2/Program-1.md
    - Program 2: Homework/Homework 2/Program-2.md
    - Program 3: Homework/Homework 2/Program-3.md
    - Program 4: Homework/Homework 2/Program-4.md
    - Program 5: Homework/Homework 2/Program-5.md
    - Program 6: Homework/Homework 2/Program-6.md
    - Program 7: Homework/Homework 2/Program-7.md
    - README: Homework/Homework 2/README.md
- Notes:
  - DataTypes: Notes/DataTypes.ipynb
  - Section 1:
    - Chapter 1: Notes/Section 1/Chapter 1.md
    - Chapter 2: Notes/Section 1/Chapter 2.md
    - Chapter 3: Notes/Section 1/Chapter 3.md
    - Chapter 4: Notes/Section 1/Chapter 4.md
  - Section 2:
    - Chapter 1: Notes/Section 2/Chapter 1.md
    - Chapter 2: Notes/Section 2/Chapter 2.md
    - Chapter 3: Notes/Section 2/Chapter 3.md
    - Chapter 4: Notes/Section 2/Chapter 4.md
  - Section 3:
    - Chapter 1: Notes/Section 3/Chapter 1.md
    - Chapter 2: Notes/Section 3/Chapter 2.md
    - Chapter 3: Notes/Section 3/Chapter 3.md
    - Chapter 4: Notes/Section 3/Chapter 4.md
    - Chapter 5: Notes/Section 3/Chapter 5.md
    - Chapter 6: Notes/Section 3/Chapter 6.md
  - Section 4:
    - Chapter 1: Notes/Section 4/Chapter 1.md
    - Chapter 2: Notes/Section 4/Chapter 2.md
    - Chapter 3: Notes/Section 4/Chapter 3.md
    - Chapter 4: Notes/Section 4/Chapter 4.md
  - Section 5:
    - Chapter 1: Notes/Section 5/Chapter 1.md
    - Chapter 2: Notes/Section 5/Chapter 2.md
    - Chapter 3: Notes/Section 5/Chapter 3.md
    - Chapter 4: Notes/Section 5/Chapter 4.md
    - Chapter 5: Notes/Section 5/Chapter 5.md
