name: Deploy MkDocs

on:
  push:
    branches:
      - master  # or 'main' if your default branch is main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install mkdocs-material pymdown-extensions mkdocs-jupyter

      - name: Build and Deploy
        run: mkdocs gh-deploy --force
